server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: auth-service-circuit-breaker
                fallbackUri: forward:/fallback/auth
        
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: ai-service-circuit-breaker
                fallbackUri: forward:/fallback/ai
        
        - id: file-storage-service
          uri: lb://file-storage-service
          predicates:
            - Path=/files/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: file-storage-circuit-breaker
                fallbackUri: forward:/fallback/files
        
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: search-service-circuit-breaker
                fallbackUri: forward:/fallback/search

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/oauth2/.well-known/oauth-authorization-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.smartdrive.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
